{{- if not .Values.security.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "paperless.fullname" . }}
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.security.secretKey }}
  secretKey: {{ .Values.security.secretKey | b64enc | quote }}
  {{- else }}
  secretKey: {{ randAlphaNum 40 | b64enc | quote }}
  {{- end }}
{{- end }}